import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f8fafc",
    paddingTop: Platform.OS === "ios" ? 50 : StatusBar.currentHeight || 0,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1e293b",
  },
  subtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 100,
  },
  topThreeContainer: {
    backgroundColor: "#fff",
    margin: 16,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1e293b",
    textAlign: "center",
    marginBottom: 20,
  },
  podiumContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  podiumItem: {
    alignItems: "center",
    flex: 1,
    marginHorizontal: 4,
  },
  firstPlace: {
    transform: [{ scale: 1.1 }],
  },
  rankBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  goldBadge: { backgroundColor: "#fbbf24" },
  silverBadge: { backgroundColor: "#9ca3af" },
  bronzeBadge: { backgroundColor: "#d97706" },
  defaultBadge: { backgroundColor: "#64748b" },
  rankBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  topUserAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#e2e8f0",
  },
  firstPlaceAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderColor: "#fbbf24",
    borderWidth: 3,
  },
  topUserAvatarPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#e2e8f0",
  },
  topUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e293b",
    textAlign: "center",
    marginBottom: 4,
  },
  firstPlaceText: {
    fontSize: 16,
    color: "#fbbf24",
  },
  topScore: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "500",
  },
  firstPlaceScore: {
    fontSize: 14,
    color: "#fbbf24",
    fontWeight: "700",
  },
  leaderboardItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginVertical: 4,
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  rankContainer: {
    width: 32,
    alignItems: "center",
    marginRight: 12,
  },
  rankNumber: {
    fontSize: 16,
    fontWeight: "700",
    color: "#64748b",
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  userAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  userInfo: { flex: 1 },
  username: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1e293b",
  },
  reportCount: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 2,
  },
  points: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3b82f6",
  },
  currentUserContainer: {
    margin: 16,
    marginTop: 24,
  },
  currentUserTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 12,
    textAlign: "center",
  },
  currentUserCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3b82f6",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  currentUserRank: {
    alignItems: "center",
    marginRight: 16,
  },
  currentUserRankText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
  },
  currentUserRankLabel: {
    fontSize: 12,
    color: "#dbeafe",
    fontWeight: "500",
  },
  currentUserAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 16,
    borderWidth: 2,
    borderColor: "#fff",
  },
  currentUserAvatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#dbeafe",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  currentUserInfo: { flex: 1 },
  currentUserName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  currentUserScore: {
    fontSize: 14,
    color: "#dbeafe",
    marginTop: 2,
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#64748b",
    marginTop: 16,
    textAlign: "center",
  },
  emptySubtext: {
    fontSize: 14,
    color: "#94a3b8",
    textAlign: "center",
    marginTop: 8,
  },
});

export default styles;
